# Site settings
title: Learning!
SEOTitle: Yunlong's Blog
header-img: img/post-bg-desk.jpg
email: lylgood@foxmail.com
description: "Capture The Flag && Security AI"
keyword: "Crypto,Web,RCE,ML,OpenNe"
url: "http://yunlongs.cn"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Yunlongs/Yunlongs.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "I want! I can! I do!"
sidebar-avatar: /img/avatar_m.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     yun-long-3-47
github_username:    Yunlongs
facebook_username:  
jianshu_username:   
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
 #Disqus（https://disqus.com/）
  #disqus_username: Yunlong

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: db87b8d1f11c6742d635                            #生成的clientID
  clientSecret: 44c2172a0f8f7422f8de626de554a5f367879d84    #生成的clientSecret
  repo: Yunlongs    #仓库名称
  owner: Yunlongs    #github用户名
  admin: Yunlongs
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 69d3be0a00c842081bce225e4b109e7b


# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "九妹",
        href: "http://www.songjiuliu.cn"
    }，
    {
        title: "刘莉莉",
        href: "https://www.liulilylily.github.io"
    }
]

theme: jekyll-theme-cayman
